FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# 1. ADD THESE ARGUMENTS SO VITE CAN SEE THEM DURING THE BUILD
ARG VITE_TMDB_API_KEY
ARG VITE_APPWRITE_PROJECT_ID
ARG VITE_APPWRITE_DATABASE_ID
ARG VITE_APPWRITE_COLLECTION_ID

ENV VITE_TMDB_API_KEY=$VITE_TMDB_API_KEY
ENV VITE_APPWRITE_PROJECT_ID=$VITE_APPWRITE_PROJECT_ID
ENV VITE_APPWRITE_DATABASE_ID=$VITE_APPWRITE_DATABASE_ID
ENV VITE_APPWRITE_COLLECTION_ID=$VITE_APPWRITE_COLLECTION_ID

# 2. Vite will now bake the real keys into the static files here:
RUN npm run build

RUN npm install -g serve

EXPOSE 3000

CMD ["serve","-s","dist","-l","3000"]
